portal_homepage:
    path:     /portal/main
    defaults: { _controller: PortalBundle:Portal:main }

portal_community:
    path:     /portal/community
    defaults: { _controller: PortalBundle:Portal:community }

portal_global:
    path:     /portal/global
    defaults: { _controller: PortalBundle:Portal:global }

portal_groups:
    path:     /portal/groups
    defaults: { _controller: PortalBundle:Portal:groups }

portal_profile:
    path:     /portal/profile
    defaults: { _controller: PortalBundle:Portal:profile }
