portal_homepage:
    path:     /portal/main/{currentforum}
    defaults: { _controller: PortalBundle:Portal:main }

portal_community:
    path:     /portal/community/{currentforum}
    defaults: { _controller: PortalBundle:Portal:community }

portal_global:
    path:     /portal/global/{currentforum}
    defaults: { _controller: PortalBundle:Portal:global }

portal_subscribed:
    path:     /portal/subscribed/{currentforum}
    defaults: { _controller: PortalBundle:Portal:subscribed }

portal_profile:
    path:     /portal/profile
    defaults: { _controller: PortalBundle:Portal:profile }

portal_profile_user:
    path:     /portal/profile/{userid}
    defaults: { _controller: PortalBundle:Portal:viewprofile }

portal_thread_create:
    path:     /portal/thread/create/{currentforum}
    defaults: { _controller: PortalBundle:Portal:threadcreate }

portal_thread:
    path:     /portal/thread/{threadid}/{currentforum}/{frompage}
    defaults: { _controller: PortalBundle:Portal:threadview }

