threadgab_database:
    resource: "@ThreadgabDatabaseBundle/Resources/config/routing.yml"
    prefix:   /

portal:
    resource: "@PortalBundle/Resources/config/routing.yml"
    prefix:   /

threadgab_login:
    resource: "@ThreadgabLoginBundle/Resources/config/routing.yml"
    prefix:   /

