parameters:
    # ...
    threadgab.controller.main.class: Threadgab\Bundle\PortalBundle\Controller\PortalController

services:
    threadgab.main.controller:
        class: "%threadgab.controller.main.class%"