Threadgab\Bundle\DatabaseBundle\Entity\ThreadgabUser:
    type: entity
    table: threadgab_user
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        facebookid:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: facebookId
        emailid:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: emailId
        zipcode:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        creationdate:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: creationDate
        photoUrl:
            type: string
            nullable: true
            length: 500
            fixed: false
            comment: ''
            column: photo_url
        signature:
            type: string
            nullable: true
            length: 1000
            fixed: false
            comment: ''
        numSub:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: num_sub
        name:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        lat:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
            default: '0'
        lng:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
            default: '0'
    lifecycleCallbacks: {  }
