threadgab_login_homepage:
    path:     /
    defaults: { _controller: ThreadgabLoginBundle:Login:index }

threadgab_login_redirect:
    path:     /redirect
    defaults: { _controller: ThreadgabLoginBundle:Login:getsession }

threadgab_userinfo_redirect:
    path:     /userinfo
    defaults: { _controller: ThreadgabLoginBundle:Login:showform }