parameters:
#    threadgab_login.example.class: Threadgab\Bundle\LoginBundle\Example

services:
#    threadgab_login.example:
#        class: %threadgab_login.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
