Threadgab\Bundle\LoginBundle\Entity\ThreadgabUser:
    type: entity
    table: threadgab_user
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        facebookid:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: facebookId
        emailid:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: emailId
        zipcode:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        creationdate:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: creationDate
    lifecycleCallbacks: {  }
