Threadgab\Bundle\PortalBundle\Entity\ThreadgabPollAnswers:
    type: entity
    table: threadgab_poll_answers
    indexes:
        fk_question_id_idx:
            columns:
                - poll_question_id
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        answerBody:
            type: string
            nullable: false
            length: 5000
            fixed: false
            comment: ''
            column: answer_body
        votes:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
        createdAt:
            type: datetime
            nullable: false
            comment: ''
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            comment: ''
            column: updated_at
    manyToOne:
        pollQuestion:
            targetEntity: ThreadgabPoll
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                poll_question_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
